version: '3'
services:
  mariadb:
    image: "mariadb:10.11"
    ports:
      - "3366:3306"
    volumes:
      - ./db/maria10/data:/var/lib/mysql
      - ./db/maria10/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  mysql8:
    image: "mysql:8.0.32"
    ports:
      - "3380:3306"
    volumes:
      - ./db/mysql8/data:/var/lib/mysql
      - ./db/mysql8/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  postgres15:
    image: "postgres:15"
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres15/data:/var/lib/postgresql/data
      - ./db/postgres15/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
